/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Model.Articulos.Medicamentos;
import Model.Articulos.Productos;
import Model.Empleados.Empleados;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author contr
 */
public class ConsultaAlmacen extends javax.swing.JFrame {
    
    Empleados empleado = new Empleados();
    Productos producto = new Productos(null);
    Medicamentos medicamento = new Medicamentos(null);
    
    String[] Titulos = {"Nombre", "Precio", "Proveedor", "En existencia", "Fecha de caducidad", "Última modificación"};
    String[][] listaMed, listaProd;
    TableRowSorter<TableModel> trs;
    
    /**
     * Creates new form StockRegalo
     */
    public ConsultaAlmacen(Empleados empleado) {
        initComponents(); 
        this.setLocationRelativeTo(null);
        setResizable(false); 
        listaProd = producto.consultarArt();
        listaMed = medicamento.consultarArt();
        //listaProd = producto.consultarArt();
        DefaultTableModel dtm_datos = new DefaultTableModel(getTblContent(listaMed, listaProd), Titulos);
        tblConsulta.setModel(dtm_datos);
        trs = new TableRowSorter<>(dtm_datos);
        tblConsulta.setRowSorter(trs);
        
        this.empleado = empleado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblConsulta = new javax.swing.JTable();
        BtnRegresar = new javax.swing.JButton();
        BtnVer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(4, 117, 204));
        jLabel3.setText("Sistema de Gestión de Compra-venta");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 157, 241));
        jLabel1.setText("Consulta de almacen");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(4, 117, 204));
        jLabel2.setText("Farmacia \"Andy\"");

        tblConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Precio", "Proveedor", "En existencia", "Fecha de caducidad", "Última modificación"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblConsulta.setEnabled(false);
        jScrollPane1.setViewportView(tblConsulta);

        BtnRegresar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnRegresar.setText("Regresar");
        BtnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegresarActionPerformed(evt);
            }
        });

        BtnVer.setBackground(new java.awt.Color(255, 204, 102));
        BtnVer.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnVer.setText("Guardar cambios");
        BtnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(45, 45, 45))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(BtnRegresar)
                        .addGap(164, 164, 164)
                        .addComponent(BtnVer))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(jLabel1)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnVer))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegresarActionPerformed
        this.dispose();
        if(empleado.getCat_empl().equals("Administrador")){
            Pantalla_Principal_Admin s_a=new Pantalla_Principal_Admin(empleado);
            s_a.setVisible(true); 
        } else{
            Pantalla_Principal_Vendedor tin=new Pantalla_Principal_Vendedor(empleado);
            tin.setVisible(true); 
        }
    }//GEN-LAST:event_BtnRegresarActionPerformed

    private void BtnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVerActionPerformed
        
    }//GEN-LAST:event_BtnVerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaAlmacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaAlmacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaAlmacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaAlmacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

    }

    public String[][] getTblContent(String [][] allContMed, String [][] allContProd){
    
        String[][] contFinal = new String[Integer.parseInt(allContMed[0][0]) + Integer.parseInt(allContProd[0][0])][6];
        for(int i = 1; i <= Integer.parseInt(allContMed[0][0]); i++){
            contFinal[i-1][0] = allContMed[i][1];
            contFinal[i-1][1] = allContMed[i][6];
            contFinal[i-1][2] = allContMed[i][7];
            contFinal[i-1][3] = allContMed[i][11];
            contFinal[i-1][4] = allContMed[i][10];
            contFinal[i-1][5] = allContMed[i][9];
        }
        int cont = Integer.parseInt(allContMed[0][0]);
        for(int i = 1; i <= Integer.parseInt(allContProd[0][0]); i++){
            contFinal[cont][0] = allContProd[i][1];
            contFinal[cont][1] = allContProd[i][3];
            contFinal[cont][2] = allContProd[i][4];
            contFinal[cont][3] = allContProd[i][8];
            contFinal[cont][4] = allContProd[i][7];
            contFinal[cont][5] = allContProd[i][6];
            cont++;
        }
        return contFinal;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnRegresar;
    private javax.swing.JButton BtnVer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblConsulta;
    // End of variables declaration//GEN-END:variables
}
