/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Model.Articulos.Medicamentos;
import Model.Articulos.Productos;
import Model.Empleados.Empleados;
import Model.Ventas.Venta;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author contr
 */
public class RegisVenta extends javax.swing.JFrame {
    
    Empleados empleado = new Empleados();
    Venta venta = new Venta();
    Medicamentos medicamento = new Medicamentos(null);
    Productos producto = new Productos(null);
    String[] Titulos = {"Código", "Nombre", "Precio", "Proveedor", "Tipo", "¿Receta?"};
    DefaultTableModel dtm_datos = new DefaultTableModel();
    TableRowSorter<TableModel> trs;
    float total = 0;
    /**
     * Creates new form RegistrarVenta
     */
    public RegisVenta(Empleados empleado) {
        initComponents(); 
        this.setLocationRelativeTo(null);
        setResizable(false);
        
        dtm_datos = new DefaultTableModel(getTblContent(medicamento.busquedaResponsivaInicial(), producto.busquedaResponsivaInicial()), Titulos);
        tblBusqProductos.setModel(dtm_datos); //ahora el modelo que ya tiene tanto los datos como los titulos lo agregamos a la tabla
        trs = new TableRowSorter<>(dtm_datos); //iniciamos el table row sorter para ordenar los datos (esto es si gustan)
        tblBusqProductos.setRowSorter(trs); //y lo agregamos al jtable
        
        this.empleado = empleado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_venta = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BtnRegresar1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        btnConfirmarVenta = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblBusqProductos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombreArt = new javax.swing.JTextField();
        btnSeleccionar = new javax.swing.JButton();
        JLabelpesos = new javax.swing.JLabel();
        txtTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabla_venta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nombre", "Precio", "Tipo ", "¿Receta?", "Cantidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla_venta);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(4, 117, 204));
        jLabel2.setText("Farmacia \"Andy\"");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(4, 117, 204));
        jLabel3.setText("Sistema de Gestión de Compra-venta");

        BtnRegresar1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnRegresar1.setText("Regresar");
        BtnRegresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegresar1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Total de la venta");

        jLabel8.setText("Cédula profesional");

        btnConfirmarVenta.setBackground(new java.awt.Color(255, 139, 144));
        btnConfirmarVenta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnConfirmarVenta.setText("Confirmar venta");
        btnConfirmarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarVentaActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 54, 220));
        jLabel5.setText("Registrar venta ");

        jInternalFrame1.setTitle("Búsqueda del produto");
        jInternalFrame1.setVisible(true);

        tblBusqProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nombre", "Precio", "Proveedor", "Tipo", "¿Receta?"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblBusqProductos);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 54, 220));
        jLabel1.setText("Búsqueda del artículo");

        jLabel4.setText("Nombre");

        txtNombreArt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreArtKeyReleased(evt);
            }
        });

        btnSeleccionar.setBackground(new java.awt.Color(153, 255, 102));
        btnSeleccionar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSeleccionar.setText("Seleccionar");
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txtNombreArt, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(10, 10, 10)))
                        .addGap(192, 192, 192))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(btnSeleccionar)
                        .addGap(223, 223, 223))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreArt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnSeleccionar)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        JLabelpesos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        JLabelpesos.setForeground(new java.awt.Color(153, 0, 0));
        JLabelpesos.setText("$");

        txtTotal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtTotal.setForeground(new java.awt.Color(153, 0, 0));
        txtTotal.setText("0.0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(30, 30, 30))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnRegresar1)
                        .addGap(155, 155, 155)
                        .addComponent(btnConfirmarVenta)
                        .addGap(112, 112, 112))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(JLabelpesos)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(86, 86, 86)
                                        .addComponent(jLabel8)))
                                .addGap(18, 18, 18)
                                .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)))
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6)
                            .addComponent(JLabelpesos)
                            .addComponent(txtTotal))
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnConfirmarVenta)
                            .addComponent(BtnRegresar1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRegresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegresar1ActionPerformed
        this.dispose();
        Pantalla_Principal_Vendedor tin=new Pantalla_Principal_Vendedor(empleado);
        tin.setVisible(true);
    }//GEN-LAST:event_BtnRegresar1ActionPerformed

    private void btnConfirmarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarVentaActionPerformed
        //Obtener datos necesarios de la tabla venta para el alta de venta
        DefaultTableModel prod_venta_tbl = (DefaultTableModel) tabla_venta.getModel();
        int num_rows = prod_venta_tbl.getRowCount();
        boolean flagAlta = true;
        if(num_rows > 0){
                String[][] art = new String[num_rows][3];

                for(int i=0; i<num_rows; i++){
                    System.out.println(prod_venta_tbl.getValueAt(i, 4).toString());
                    if(txtCedula.equals("") && prod_venta_tbl.getValueAt(i, 4).toString().equals("SI")){
                        JOptionPane.showMessageDialog(null, "Es necesario registrar la cédula profesional perteneciente a la receta médica");
                        flagAlta = false;
                        break;
                    } else{
                        art[i][0] = prod_venta_tbl.getValueAt(i, 0).toString();
                        art[i][1] = prod_venta_tbl.getValueAt(i, 5).toString();
                        art[i][2] = prod_venta_tbl.getValueAt(i, 2).toString();
                    }
                }
                if(flagAlta){
                    venta.setTotal_venta(Float.parseFloat(txtTotal.getText()));
                    venta.setCedula_venta(txtCedula.getText());
                    flagAlta = venta.altaVenta(empleado.getNum_empl(), art, num_rows);

                    if(flagAlta){
                        JOptionPane.showMessageDialog(null, "Registro de venta exitoso");
                    } else{
                        JOptionPane.showMessageDialog(null, "Registro fallido, intenta de nuevo");
                    }
                }
            
        } else{
            JOptionPane.showMessageDialog(null, "Debes seleccionar productos para realizar la venta");
        }
    }//GEN-LAST:event_btnConfirmarVentaActionPerformed

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
        int row = tblBusqProductos.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) tblBusqProductos.getModel();
        DefaultTableModel tbl_venta = (DefaultTableModel) tabla_venta.getModel();
        String M_datos[] =  new String[6];
        if(row >= 0){
            M_datos[0] = model.getValueAt(row, 0).toString();
            M_datos[1] = model.getValueAt(row, 1).toString();
            M_datos[2] = model.getValueAt(row, 2).toString();
            M_datos[3] = model.getValueAt(row, 4).toString();
            M_datos[4] = model.getValueAt(row, 5).toString();
            M_datos[5] = "1";
        }
        SetTableProdCont(M_datos);
        
        //suma del total de la venta
        String cant = JOptionPane.showInputDialog(null, "Cantidad a vender:", "Cantidad", JOptionPane.PLAIN_MESSAGE, null, null, "1").toString();
        tbl_venta.setValueAt(cant, tbl_venta.getRowCount()-1, 5);
        total = total + (Float.parseFloat(model.getValueAt(row, 2).toString()) * Float.parseFloat(cant));
        txtTotal.setText(String.valueOf(total));
    }//GEN-LAST:event_btnSeleccionarActionPerformed

    private void txtNombreArtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreArtKeyReleased
        //Llenamos la tabla con los proveedores similares
        String nombre = "" + txtNombreArt.getText();//aqui obtenemos cada letra que ingresemos en el textfield en tiempo real
        dtm_datos = new DefaultTableModel(getTblContent(medicamento.busquedaResponsivaArt(nombre), producto.busquedaResponsivaArt(nombre)), Titulos);
        tblBusqProductos.setModel(dtm_datos);
        trs = new TableRowSorter<>(dtm_datos);
        tblBusqProductos.setRowSorter(trs);
    }//GEN-LAST:event_txtNombreArtKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

    }
    
    public String[][] getTblContent(String [][] allContMed, String [][] allContProd){
    
        String[][] contFinal = new String[Integer.parseInt(allContMed[0][0]) + Integer.parseInt(allContProd[0][0])][6];
        for(int i = 1; i <= Integer.parseInt(allContMed[0][0]); i++){
            contFinal[i-1][0] = allContMed[i][0];
            contFinal[i-1][1] = allContMed[i][1];
            contFinal[i-1][2] = allContMed[i][2];
            contFinal[i-1][3] = allContMed[i][3];
            contFinal[i-1][4] = allContMed[i][4];
            contFinal[i-1][5] = allContMed[i][5];
        }
        int cont = Integer.parseInt(allContMed[0][0]);
        for(int i = 1; i <= Integer.parseInt(allContProd[0][0]); i++){
            contFinal[cont][0] = allContProd[i][0];
            contFinal[cont][1] = allContProd[i][1];
            contFinal[cont][2] = allContProd[i][2];
            contFinal[cont][3] = allContProd[i][3];
            contFinal[cont][4] = allContProd[i][4];
            contFinal[cont][5] = allContProd[i][5];
            cont++;
        }
        return contFinal;
    }
    
    public static void SetTableProdCont(String[] rowSelected){
        DefaultTableModel dtm_datos = (DefaultTableModel) tabla_venta.getModel();
        dtm_datos.addRow(rowSelected);
        tabla_venta.setModel(dtm_datos);
        TableRowSorter<TableModel> trs = new TableRowSorter<>(dtm_datos);
        tabla_venta.setRowSorter(trs);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnRegresar1;
    private javax.swing.JLabel JLabelpesos;
    private javax.swing.JButton btnConfirmarVenta;
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private static javax.swing.JTable tabla_venta;
    private javax.swing.JTable tblBusqProductos;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtNombreArt;
    private javax.swing.JLabel txtTotal;
    // End of variables declaration//GEN-END:variables
}
