/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Model.Articulos.Articulos;
import Model.Articulos.Medicamentos;
import Model.Articulos.Productos;
import Model.Compras.Proveedores;
import Model.Empleados.Empleados;
import UI.Pantalla_Principal_Admin;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author contr
 */
public class RegistrarArticulos extends javax.swing.JFrame {
    
    Empleados empleado = new Empleados();
    /**
     * Creates new form RegistrarProd
     */
    public RegistrarArticulos(Empleados empleado) {
        initComponents();
        this.setLocationRelativeTo(null);
        setResizable(false); 
        
        this.empleado = empleado;
        
        jPanelArtMedicamento.setVisible(false);
        jPanelArtProducto.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNombre = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BtnRegresar = new javax.swing.JButton();
        cmbTipo = new javax.swing.JComboBox<>();
        BtnConfirmar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnSelectProv = new javax.swing.JButton();
        txtProveedor = new javax.swing.JTextField();
        jPanelArtMedicamento = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cmbTipoMed = new javax.swing.JComboBox<>();
        cmbPresntMed = new javax.swing.JComboBox<>();
        txtGramajeMed = new javax.swing.JTextField();
        cmbGramajeMed = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        cmbRecetaMed = new javax.swing.JComboBox<>();
        jPanelArtProducto = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        cmbCategoriaProd = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        spnrExistencia = new javax.swing.JSpinner();
        spnrDay = new javax.swing.JSpinner();
        spnrMonth = new javax.swing.JSpinner();
        spnrYear = new javax.swing.JSpinner();
        jLabel15 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 54, 220));
        jLabel1.setText("Registrar artículos");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(4, 117, 204));
        jLabel2.setText("Farmacia \"Andy\"");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(4, 117, 204));
        jLabel3.setText("Sistema de Gestión de Compra-venta");

        BtnRegresar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnRegresar.setText("Regresar");
        BtnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegresarActionPerformed(evt);
            }
        });

        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Medicamento", "Producto" }));
        cmbTipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbTipoItemStateChanged(evt);
            }
        });
        cmbTipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cmbTipoMouseReleased(evt);
            }
        });
        cmbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoActionPerformed(evt);
            }
        });

        BtnConfirmar.setBackground(new java.awt.Color(255, 139, 144));
        BtnConfirmar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnConfirmar.setText("Confirmar producto");
        BtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConfirmarActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Precio", "Proveedor", "Tipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel4.setText("Nombre");

        jLabel5.setText("Precio");

        jLabel7.setText("Tipo");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Nombre del proveedor");

        btnSelectProv.setBackground(new java.awt.Color(153, 204, 255));
        btnSelectProv.setText("Seleccionar proveedor");
        btnSelectProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectProvActionPerformed(evt);
            }
        });

        txtProveedor.setEditable(false);
        txtProveedor.setEnabled(false);
        txtProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProveedorActionPerformed(evt);
            }
        });

        jLabel6.setText("Tipo de medicamento");

        jLabel9.setText("Presentación");

        jLabel10.setText("Gramaje");

        cmbTipoMed.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Antibiotico", "Psicotrópico", "Antiviral" }));

        cmbPresntMed.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Capsula", "Pastilla", "Jarabe", "Ampoyeta" }));

        txtGramajeMed.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtGramajeMedKeyReleased(evt);
            }
        });

        cmbGramajeMed.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MG", "ML" }));

        jLabel11.setText("¿Requiere receta?");

        cmbRecetaMed.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));

        javax.swing.GroupLayout jPanelArtMedicamentoLayout = new javax.swing.GroupLayout(jPanelArtMedicamento);
        jPanelArtMedicamento.setLayout(jPanelArtMedicamentoLayout);
        jPanelArtMedicamentoLayout.setHorizontalGroup(
            jPanelArtMedicamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelArtMedicamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelArtMedicamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanelArtMedicamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelArtMedicamentoLayout.createSequentialGroup()
                        .addGroup(jPanelArtMedicamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbTipoMed, 0, 95, Short.MAX_VALUE)
                            .addComponent(cmbPresntMed, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtGramajeMed))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbGramajeMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cmbRecetaMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelArtMedicamentoLayout.setVerticalGroup(
            jPanelArtMedicamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelArtMedicamentoLayout.createSequentialGroup()
                .addGroup(jPanelArtMedicamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbTipoMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelArtMedicamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cmbPresntMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelArtMedicamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtGramajeMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbGramajeMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelArtMedicamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cmbRecetaMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 3, Short.MAX_VALUE))
        );

        jLabel12.setText("Categoría del producto");

        cmbCategoriaProd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Perfumeria", "Regalo" }));

        javax.swing.GroupLayout jPanelArtProductoLayout = new javax.swing.GroupLayout(jPanelArtProducto);
        jPanelArtProducto.setLayout(jPanelArtProductoLayout);
        jPanelArtProductoLayout.setHorizontalGroup(
            jPanelArtProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelArtProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbCategoriaProd, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 50, Short.MAX_VALUE))
        );
        jPanelArtProductoLayout.setVerticalGroup(
            jPanelArtProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelArtProductoLayout.createSequentialGroup()
                .addGroup(jPanelArtProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cmbCategoriaProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 94, Short.MAX_VALUE))
        );

        jLabel13.setText("Fecha de caducidad");

        jLabel14.setText("Cantidad en existencia");

        spnrExistencia.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        spnrDay.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));

        spnrMonth.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));

        spnrYear.setModel(new javax.swing.SpinnerListModel(new String[] {"2024", "2025", "2026", "2027"}));

        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Año/Mes/Día");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(256, 256, 256)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 50, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addGap(96, 96, 96)
                                                .addComponent(txtPrecio))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addGap(88, 88, 88)
                                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                    .addGap(125, 125, 125)
                                                    .addComponent(btnSelectProv, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel7)
                                                        .addComponent(jLabel13))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(31, 31, 31))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel14)
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(spnrYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(spnrMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(spnrDay, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(spnrExistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(jLabel15))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanelArtMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanelArtProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(BtnRegresar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnSelectProv))
                    .addComponent(jPanelArtMedicamento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(spnrDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spnrMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spnrYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(spnrExistencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanelArtProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnRegresar)
                    .addComponent(BtnConfirmar))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void SetTxtNomProveedor(String nombre){
        txtProveedor.setText(nombre);
    }
    
    private void BtnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegresarActionPerformed
        this.dispose();
        Pantalla_Principal_Admin tin=new Pantalla_Principal_Admin(empleado);
        tin.setVisible(true);
    }//GEN-LAST:event_BtnRegresarActionPerformed

    private void BtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConfirmarActionPerformed
        
        //Obtenemos la fecha actual
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("uuuu-MM-dd");
        LocalDate localDate = LocalDate.now();
        
       if(cmbTipo.getSelectedItem().toString().equals("Medicamento")){
           
           //genero obj proveedor para inicializar obj medicamento
               Proveedores prov = new Proveedores();
               prov.setNom_prov(txtProveedor.getText());
               String cad;
               boolean flagAlta, receta;
               /*  --------------------------  DESDE AQUÍ HAY QUE EMPEZAR A MODIFICAR  ------------------------  */
               Medicamentos medicamento = new Medicamentos(prov);
               medicamento.setNom_art(txtNombre.getText());
               medicamento.setPrecio_art(Float.parseFloat(txtPrecio.getText()));
               medicamento.setTipo_med(cmbTipoMed.getSelectedItem().toString());
               medicamento.setPresen_med(cmbPresntMed.getSelectedItem().toString());
               medicamento.setGram_med(txtGramajeMed.getText() +" "+ cmbGramajeMed.getSelectedItem().toString());
               //conversion de selección receta
               if(cmbRecetaMed.getSelectedItem().toString().equals("Si")){
                   receta = true;
               } else{
                   receta = false;
               }
               medicamento.setReceta_med(receta);
               cad = spnrYear.getValue().toString() + "-";
               //Mantiene uniformidad en la fecha para el registro en BD
               if((Integer)spnrMonth.getValue() < 10){
                   cad = cad + "0" + spnrMonth.getValue().toString() + "-";
               }else{
                   cad = cad + spnrMonth.getValue().toString() + "-";
               }
               cad = cad + spnrDay.getValue().toString();
               
               medicamento.altaAlmacen(dtf.format(localDate), cad, (Integer)spnrExistencia.getValue());
               flagAlta = medicamento.altaArt();
               if(flagAlta == true){
                   JOptionPane.showConfirmDialog(null, "Registro exitoso"); //registro en BD exitoso
                   
                   //Añadimos registro a la tabla
                   DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
                   model.addRow(new Object[]{medicamento.getNom_art(), medicamento.getPrecio_art(), prov.getNom_prov(), "Medicamento"});
               } else{
                   JOptionPane.showConfirmDialog(null, "Registro fallido, intenta de nuevo");
               }
               
               //Eliminar toda selección
               txtNombre.setText(null);
               txtPrecio.setText(null);
               txtProveedor.setText(null);
               txtGramajeMed.setText(null);
               cmbTipo.setSelectedItem(null);
               cmbCategoriaProd.setSelectedItem(null);
               cmbGramajeMed.setSelectedItem(null);
               cmbPresntMed.setSelectedItem(null);
               cmbRecetaMed.setSelectedItem(null);
               cmbTipoMed.setSelectedItem(null);
               spnrDay.setValue(1);
               spnrExistencia.setValue(1);
               spnrMonth.setValue(1);
               spnrYear.setValue("2024");
           
       } else {
           if(cmbTipo.getSelectedItem().toString().equals("Producto")){
               
               //genero obj proveedor para inicializar obj producto
               Proveedores prov = new Proveedores();
               prov.setNom_prov(txtProveedor.getText());
               String cad;
               boolean flagAlta;
               
               Productos producto = new Productos(prov);
               producto.setNom_art(txtNombre.getText());
               producto.setPrecio_art(Float.parseFloat(txtPrecio.getText()));
               producto.setCat_product(cmbCategoriaProd.getSelectedItem().toString());
               cad = spnrYear.getValue().toString() + "-";
               //Mantiene uniformidad en la fecha para el registro en BD
               if((Integer)spnrMonth.getValue() < 10){
                   cad = cad + "0" + spnrMonth.getValue().toString() + "-";
               }else{
                   cad = cad + spnrMonth.getValue().toString() + "-";
               }
               cad = cad + spnrDay.getValue().toString();
               
               producto.altaAlmacen(dtf.format(localDate), cad, (Integer)spnrExistencia.getValue());
               flagAlta = producto.altaArt();
               if(flagAlta == true){
                   JOptionPane.showConfirmDialog(null, "Registro exitoso"); //registro en BD exitoso
                   
                   //Añadimos registro a la tabla
                   DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
                   model.addRow(new Object[]{producto.getNom_art(), producto.getPrecio_art(), prov.getNom_prov(), "Producto"});
               } else{
                   JOptionPane.showConfirmDialog(null, "Registro fallido, intenta de nuevo");
               }
               
               //Eliminar toda selección
               txtNombre.setText(null);
               txtPrecio.setText(null);
               txtProveedor.setText(null);
               txtGramajeMed.setText(null);
               cmbTipo.setSelectedIndex(0);
               cmbCategoriaProd.setSelectedIndex(0);
               cmbGramajeMed.setSelectedIndex(0);
               cmbPresntMed.setSelectedIndex(0);
               cmbRecetaMed.setSelectedIndex(0);
               cmbTipoMed.setSelectedIndex(0);
               spnrDay.setValue(1);
               spnrExistencia.setValue(1);
               spnrMonth.setValue(1);
               spnrYear.setValue("2024");
               
           } else{
               JOptionPane.showMessageDialog(null, "Elige un tipo de artículo ");
           }
       }
    }//GEN-LAST:event_BtnConfirmarActionPerformed

    private void btnSelectProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectProvActionPerformed
        BusquedaProveedor vw_BusquedaProv = new BusquedaProveedor();
        vw_BusquedaProv.setVisible(true);
        vw_BusquedaProv.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btnSelectProvActionPerformed

    private void txtProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProveedorActionPerformed

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void txtGramajeMedKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGramajeMedKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGramajeMedKeyReleased

    private void cmbTipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbTipoItemStateChanged
        
    }//GEN-LAST:event_cmbTipoItemStateChanged

    private void cmbTipoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbTipoMouseReleased
        
    }//GEN-LAST:event_cmbTipoMouseReleased

    private void cmbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoActionPerformed
        if(cmbTipo.getSelectedItem().toString().equals("Medicamento")){
           jPanelArtMedicamento.setVisible(true);
           jPanelArtProducto.setVisible(false);
        } else {
           if(cmbTipo.getSelectedItem().toString().equals("Producto")){
               jPanelArtMedicamento.setVisible(false);
               jPanelArtProducto.setVisible(true);
            }
        }
    }//GEN-LAST:event_cmbTipoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnConfirmar;
    private javax.swing.JButton BtnRegresar;
    private javax.swing.JButton btnSelectProv;
    private javax.swing.JComboBox<String> cmbCategoriaProd;
    private javax.swing.JComboBox<String> cmbGramajeMed;
    private javax.swing.JComboBox<String> cmbPresntMed;
    private javax.swing.JComboBox<String> cmbRecetaMed;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JComboBox<String> cmbTipoMed;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelArtMedicamento;
    private javax.swing.JPanel jPanelArtProducto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JSpinner spnrDay;
    private javax.swing.JSpinner spnrExistencia;
    private javax.swing.JSpinner spnrMonth;
    private javax.swing.JSpinner spnrYear;
    private javax.swing.JTextField txtGramajeMed;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    private static javax.swing.JTextField txtProveedor;
    // End of variables declaration//GEN-END:variables
}
